CREATE MULTISET VOLATILE TABLE MAUS, NO LOG AS
(
SELECT 	CUS_CUST_ID,
				MAX(CASE 
				WHEN PHOTO_MES = '201812' AND ZEROIFNULL(DAYS_MAU_MP) > 0 THEN 1
				ELSE 0
				END )AS MAU_MP_M3,
				MAX(CASE 
				WHEN PHOTO_MES = '201901' AND ZEROIFNULL(DAYS_MAU_MP) > 0 THEN 1
				ELSE 0
				END) AS MAU_MP_M2,
				MAX(CASE 
				WHEN PHOTO_MES = '201902' AND ZEROIFNULL(DAYS_MAU_MP) > 0 THEN 1
				ELSE 0
				END) AS MAU_MP_M1,
				MAX(CASE 
				WHEN PHOTO_MES = '201812' AND ZEROIFNULL(DAYS_MAU_ML) > 0 THEN 1
				ELSE 0
				END) AS MAU_ML_M3,
				MAX(CASE 
				WHEN PHOTO_MES = '201901' AND ZEROIFNULL(DAYS_MAU_ML) > 0 THEN 1
				ELSE 0
				END) AS MAU_ML_M2,
				MAX(CASE 
				WHEN PHOTO_MES = '201902' AND ZEROIFNULL(DAYS_MAU_ML) > 0 THEN 1
				ELSE 0
				END) AS MAU_ML_M1,
				SUM(CASE 
				WHEN PHOTO_MES = '201812' AND ZEROIFNULL(DAYS_MAU_ML) + ZEROIFNULL(DAYS_MAU_MP) > 0 THEN 1
				ELSE 0
				END) AS MAU_M3,
				SUM(CASE 
				WHEN PHOTO_MES = '201901' AND ZEROIFNULL(DAYS_MAU_ML) + ZEROIFNULL(DAYS_MAU_MP) > 0 THEN 1
				ELSE 0
				END) AS MAU_M2,
				SUM(CASE
				WHEN PHOTO_MES = '201902' AND ZEROIFNULL(DAYS_MAU_ML) + ZEROIFNULL(DAYS_MAU_MP) > 0 THEN 1
				ELSE 0
				END) AS MAU_M1,
				SUM(CASE
				WHEN PHOTO_MES = '201812' THEN ZEROIFNULL(DAYS_MAU_ML) + ZEROIFNULL(DAYS_MAU_MP)
				ELSE 0
				END) AS DAYS_MAU_M3,
				SUM(CASE
				WHEN PHOTO_MES = '201901' THEN ZEROIFNULL(DAYS_MAU_ML) + ZEROIFNULL(DAYS_MAU_MP)
				ELSE 0
				END) AS DAYS_MAU_M2,
				SUM(CASE
				WHEN PHOTO_MES = '201902' THEN ZEROIFNULL(DAYS_MAU_ML) + ZEROIFNULL(DAYS_MAU_MP)
				ELSE 0
				END) AS DAYS_MAU_M1
FROM		WHOWNER.LK_WALLET_MAUS
WHERE		SIT_SITE_ID = 'MLA'
				AND PHOTO_MES BETWEEN '201812' AND '201902'
GROUP BY 1
) WITH DATA UNIQUE PRIMARY INDEX (CUS_CUST_ID) ON COMMIT PRESERVE ROWS